[project]
name = "granite-3.3-8b-instruct"
version = "1.1.4"
description = "Dependencies for predict.py"
dependencies = [
    "vllm[flashinfer]==0.10.2",
]
requires-python = "~= 3.12.0"

# This needs to match the CUDA version in cog.yaml
[tool.uv.pip]
torch-backend = "cu128"
