[project]
name = "granite-3.3-8b-instruct"
version = "1.1.3"
description = "Dependencies for predict.py"
dependencies = [
    "vllm[flashinfer]==0.10.1.1",
]
requires-python = "~= 3.12.0"

# This needs to match the CUDA version in cog.yaml
[tool.uv.pip]
torch-backend = "cu128"
