# SPDX-License-Identifier: Apache-2.0

[project]
name = "granite-4.2-8b"
version = "1.0.0"
description = "Dependencies for run.py"
dependencies = [
    # "vllm==0.24.0" # <== This is built for CUDA 13
    "vllm @ https://github.com/vllm-project/vllm/releases/download/v0.24.0/vllm-0.24.0+cu129-cp38-abi3-manylinux_2_28_x86_64.whl"

]
requires-python = "~= 3.13.0"

# This needs to match the CUDA version in cog.yaml
[tool.uv.pip]
torch-backend = "cu129"
