[project]
name = "granite-speech-3.3-8b"
version = "1.0.1"
description = "Dependencies for predict.py"
dependencies = [
    "cog==0.15.10",
    "vllm==0.9.2",
    "librosa==0.11.0",
]
requires-python = "~= 3.12.0"
