# SPDX-License-Identifier: Apache-2.0

[project]
name = "granite-4.0-tiny-preview"
version = "1.0.0"
description = "Dependencies for predict.py"
dependencies = [
    "cog==0.15.10",
    "vllm==0.9.2",
]
requires-python = "~= 3.12.0"
